const fs = require("fs");
const path = require("path");
const { PDFParse } = require("pdf-parse");

const englishBase = "d:/TaiLieu_HocKy/Nam_4/HocKy_2/QuanLy_DuAn/Slide";
const vietnameseBase = "c:/Users/skyga/Downloads";

const sources = [
  {
    id: "cost",
    chapter: 7,
    title: "Project Cost Management",
    viTitle: "Quản lý chi phí dự án",
    english: path.join(englishBase, "itpm07-140329000758-phpapp02.pdf"),
    vietnamese: path.join(vietnameseBase, "Chapter_07_Tips.pdf"),
  },
  {
    id: "hr",
    chapter: 9,
    title: "Project Human Resource Management",
    viTitle: "Quản lý nguồn nhân lực dự án",
    english: path.join(englishBase, "itpm09-140329000826-phpapp02.pdf"),
    vietnamese: path.join(vietnameseBase, "Chapter_09_Tips.pdf"),
  },
  {
    id: "communications",
    chapter: 10,
    title: "Project Communications Management",
    viTitle: "Quản lý truyền thông dự án",
    english: path.join(englishBase, "itpm10-140329000837-phpapp02.pdf"),
    vietnamese: path.join(vietnameseBase, "Chapter_10_Tips.pdf"),
  },
  {
    id: "risk",
    chapter: 11,
    title: "Project Risk Management",
    viTitle: "Quản lý rủi ro dự án",
    english: path.join(englishBase, "itpm11-risk-phpapp02.pdf"),
    vietnamese: path.join(vietnameseBase, "Chapter_11_Tips.pdf"),
  },
  {
    id: "procurement",
    chapter: 12,
    title: "Project Procurement Management",
    viTitle: "Quản lý mua sắm dự án",
    english: path.join(englishBase, "itpm12-140329000646-phpapp02.pdf"),
    vietnamese: path.join(vietnameseBase, "Chapter_12_Tips_1.pdf"),
  },
  {
    id: "stakeholders",
    chapter: 13,
    title: "Project Stakeholder Management",
    viTitle: "Quản lý bên liên quan dự án",
    english: path.join(englishBase, "itpm13-140329000647-phpapp02.pdf"),
    vietnamese: path.join(vietnameseBase, "Chapter_13_Tips_1.pdf"),
  },
];

function cleanText(text) {
  return text
    .replace(/\r/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function splitPages(text) {
  const pages = [];
  const regex = /--\s*(\d+)\s+of\s+\d+\s*--/g;
  let match;
  let lastIndex = 0;
  let lastPage = 1;

  while ((match = regex.exec(text)) !== null) {
    const chunk = text.slice(lastIndex, match.index).trim();
    if (chunk) {
      pages.push({ page: lastPage, text: cleanText(chunk) });
    }
    lastPage = Number(match[1]) + 1;
    lastIndex = regex.lastIndex;
  }

  const finalChunk = text.slice(lastIndex).trim();
  if (finalChunk) {
    pages.push({ page: lastPage, text: cleanText(finalChunk) });
  }

  return pages.map((page, index) => ({ ...page, page: index + 1 }));
}

async function extractPdf(filePath) {
  const buffer = fs.readFileSync(filePath);
  const parser = new PDFParse({ data: buffer });
  const info = await parser.getInfo({ parsePageInfo: true });
  const result = await parser.getText();
  await parser.destroy();

  const text = cleanText(result.text);
  return {
    file: filePath,
    pages: info.total || splitPages(text).length,
    text,
    pageTexts: splitPages(text),
  };
}

async function main() {
  const extracted = [];
  for (const source of sources) {
    const [english, vietnamese] = await Promise.all([
      extractPdf(source.english),
      extractPdf(source.vietnamese),
    ]);
    extracted.push({ ...source, english, vietnamese });
    console.log(
      `${source.chapter}. ${source.title}: ${english.pages} English pages, ${vietnamese.pages} Vietnamese pages`,
    );
  }

  const targetDir = path.join(process.cwd(), "src", "data");
  fs.mkdirSync(targetDir, { recursive: true });
  const target = path.join(targetDir, "sourceSlides.js");
  const body = `// Generated by scripts/extract-pdfs.cjs from the local course PDFs.\nexport const sourceSlides = ${JSON.stringify(
    extracted,
    null,
    2,
  )};\n`;
  fs.writeFileSync(target, body, "utf8");
  console.log(`Wrote ${path.relative(process.cwd(), target)}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
